# Generated by Django 5.1.5 on 2026-06-21 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Módulo (catálogo)',
                'verbose_name_plural': 'Módulos (catálogo)',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('usuarios_incluidos', models.PositiveIntegerField()),
                ('precio_mensual_cop', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modulos_incluidos', models.ManyToManyField(blank=True, related_name='planes', to='plataforma.modulocatalogo')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['precio_mensual_cop'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='plataforma.plan'),
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios_adicionales', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_proximo_pago', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('mora', 'En mora'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='activa', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='plataforma.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='plataforma.tenant')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
